version: '3.7'

services:
  backend:
    image: lkt9899/drwa:backend
    container_name: drwa-backend
    ports:
      - 18081:8081
    stdin_open: true
    tty: true
    environment:
      USE_PROFILE: ${USE_PROFILE}
    networks:
      - drwa
      
  frontend:
    image: lkt9899/drwa:frontend
    container_name: drwa-frontend
    ports:
      - 13030:3000
    stdin_open: true
    tty: true
    networks:
      - drwa

  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    restart: unless-stopped
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./elasticsearch/data:/usr/share/elasticsearch/data:Z
      # - ./cert/ca.crt:/usr/share/elasticsearch/config/ca.crt:ro,z
      # - ./cert/elasticsearch.crt:/usr/share/elasticsearch/config/elasticsearch.crt:ro,z
      # - ./cert/elasticsearch.key:/usr/share/elasticsearch/config/elasticsearch.key:ro,z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - drwa

networks:
  drwa:
    external: true

volumes:
  drwa:
